fix bug: redirection
needed "redirect:/{viewname}" instead of just "{viewname}"

update:
all pages work and redirect as they should, except that the unassign
button doesn't work for some animals.
It'll work for animals I assign a schedule to after their creation, but
not for those assigned to one when they are first entered in.  see error
below
'''
ERROR: insert or update on table "animals" violates foreign key
constraint "animals_feeding_schedule_fkey"
  Detail: Key (feeding_schedule)=(0) is not present in table
"feeding_schedules".
'''